### ISSUE TITLE
cachix fails to upload musl artifacts in github actions on macos

### ISSUE THREAD

**Issue by cpcloud** [cachix/cachix-action#103]
Here's a CI run demonstrating the issue.

It looks like cachix can't read symlinks produced by the (successful) build. This only happens on macos and only when building musl artifacts.

https://github.com/cpcloud/protoletariat/runs/4576549612?check_suite_focus=true

**Comment by cpcloud** [comment]
Another interesting bit of information is that it seems to be even more narrow: only the ld artifact from the build is failing to upload. Other musl artifacts upload just fine. E.g., https://github.com/cpcloud/protoletariat/runs/4576549477?check_suite_focus=true

**Comment by domenkozar** [comment]
This is going to be fixed in Cachix 1.7, due to release tomorrow.
