### ISSUE TITLE
support use of a post-build-hook so that failing builds can still take advantage of cachix

### ISSUE THREAD

**Issue by cpcloud** [cachix/cachix-action#104]
When builds fail it would be nice to be able to still cache the derivations that successfully built along the way.

I understand that `cachix watch` would be close to this, but it doesn't work in PRs from forks, which requires rewriting all existing code to use `cachix watch` and handling the fork runs.

**Comment by domenkozar** [comment]
https://blog.cachix.org/posts/2024-01-12-cachix-v1-7/
