### ISSUE TITLE
don't stop uploading artifacts on the first failure

### ISSUE THREAD

**Issue by flokli** [cachix/cachix-action#111]
Right now, `push-paths.sh` immediately exits if there's an error uploading a path (as can be seen in https://github.com/cachix/cachix-action/issues/106).

This means, CI unnecessarily rebuilds stuff that could have been uploaded.

Could `dist/main/push-paths.sh` try uploading the other paths, instead of stopping on the first failing one?

**Comment by domenkozar** [comment]
This is fixed in Cachix 1.0
