### ISSUE TITLE
Upload dependencies to cachix even when the build has failed

### ISSUE THREAD

**Issue by utdemir** [cachix/cachix-action#12]
It would be great if `cachix-action` uploads the built derivations even if the final build has failed.

My usecase is that, I am building a derivation with tons of third party dependencies, and if one of them fails on GitHub actions, `cachix-action` does not upload the transitive dependencies and I have to rebuild them in order to debug the build on my computer.

Probably relevant: #10

**Comment by domenkozar** [comment]
I agree - will try to get #10 done :)

**Comment by domenkozar** [comment]
I've just released v3 that fixes this.
