### ISSUE TITLE
Caching `nix-shell`?

### ISSUE THREAD

**Issue by jwoudenberg** [cachix/cachix-action#13]
First, awesome project, thank you!

I have a question / feature request (not sure which yet).

I'm working on a repo that's not (yet) using a `default.nix` to build the project, but is using a `shell.nix` to set up a development environment. This Github action looks like a perfect tool to automatically keep the cache of the environment up to date so users of the repo don't need to build the environment themselves.

Is there a way to run use this action to build a `shell.nix` rather than a `default.nix` file?

**Comment by domenkozar** [comment]
There's an open issue to document this at cachix: https://github.com/cachix/cachix/issues/52#issuecomment-396935563

This seems like another use case for #8

**Comment by domenkozar** [comment]
I've just released v3 that will also cache `nix-shell` calls.
