### ISSUE TITLE
Unable to locate file: cachix

### ISSUE THREAD

**Issue by tricktron** [cachix/cachix-action#139]
The Cachix Action suddenly fails with:

```console
Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

See [failing workflow](https://github.com/tricktron/openapi2jsonschema/actions/runs/4295778524/jobs/7486650150).

Since everything was working before without any code change, my guess is that error may be network related in the 
`/usr/bin/bash -c nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install` step.

**Comment by rvolosatovs** [comment]
Duplicate of #138

**Comment by tricktron** [comment]
Closed as duplicate because @rvolosatovs was 2 minutes faster😃.
