### ISSUE TITLE
Action started failing ~36 hours ago

### ISSUE THREAD

**Issue by samuela** [cachix/cachix-action#143]
I have not made any changes to my GitHub Actions config, but recently I've started seeing my CI fail on the cachix-action step:
```
Cachix: installing
  /usr/bin/bash -c nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
Cachix: checking version
  Error: Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
For example, check out [this run](https://github.com/samuela/nixpkgs-upkeep/actions/runs/4309462134/jobs/7516882365).

Any idea what's causing these failures? How can I get cachix-action working again?

**Comment by samuela** [comment]
thanks, I'll give that a shot!

**Comment by samuela** [comment]
that seems to have fixed it: https://github.com/samuela/nixpkgs-upkeep/actions/runs/4310823350

thanks @sandydoo !

**Comment by pujvz** [comment]
Hi I am experiencing this error as well while using github actions. My last action from 4 days ago was successful, but it started failing today. How did you upgrade cachix/install-nix-action @samuela ? I am using a clone of this repository https://github.com/moergo-sc/glove80-zmk-config
![asdf](https://user-images.githubusercontent.com/105397306/231362180-c68076b8-dcca-499e-ae66-73445092af5b.png)

Please let me know if I should open a separate issue.

**Comment by samuela** [comment]
@pujvz You'll need to update your GH Actions config. See eg the `cachix/cachix-action@v12` in your screenshot above.

**Comment by pujvz** [comment]
@samuela I tried updating my build.yml yesterday and the action errored out. Sorry if I am missing something extremely obvious. I am not a SWE and I'm new to all this.

build.yml
![fdsa](https://user-images.githubusercontent.com/105397306/231560850-9dacbf7a-6d4a-4b25-a6af-2fd994a5d86b.png)

Action error after updating build.yml
![asdf](https://user-images.githubusercontent.com/105397306/231560365-ea4bd68f-5760-4f75-a295-2f1653017215.png)

**Comment by samuela** [comment]
hmm this sort of thing really belongs in a separate issue. a few thoughts in the meantime:
* please post links to the relevant logs/commits/etc instead of screenshots. this helps to debug.
* it looks like you downgraded from v20 to v12. you want to be upgrading versions if at all possible

**Comment by pujvz** [comment]
Apologies. I attached a screenshot of the wrong commit from after I reverted the change. Another user was able to assist me with this issue. I changed line 17 from `    - uses: cachix/install-nix-action@v18` to `    - uses: cachix/install-nix-action@v20`, and now the action completes successfully.
