### ISSUE TITLE
Any way to not even have to download anything?

### ISSUE THREAD

**Issue by dpc** [cachix/cachix-action#145]
Some derivations in CI pipelines are only used to make sure they build successfully, and they don't change that often.

However when using `nix build ...`, even if a derivation was built before and is in cachix, all the artifacts will be downloaded ... just to throw them away immediately.

Is there a way to make nix not download anything if a given derivation is already in a binary cache? That would save a lot of time and probably bandwidth.

Some:

```
nix build --do-nothing-if-exists-in-cache
```

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nix/issues/3946 for different attempts at building this.

https://github.com/nix-community/nix-eval-jobs is the closest it gets to get this to work (you do need an extra binary besides Nix, that's the downside).

**Comment by dpc** [comment]
Thank you.
