### ISSUE TITLE
Syntax error when cachix-action runs

### ISSUE THREAD

**Issue by 573** [cachix/cachix-action#159]
Getting
>Run cachix/cachix-action@v11
  with:
    name: 573-bc
    authToken: ***
  env:
    NIX_PROFILES: /nix/var/nix/profiles/default /home/runner/.nix-profile
    NIX_USER_PROFILE_DIR: /nix/var/nix/profiles/per-user/runner
    NIX_SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    NIX_USER_CONF_FILES: /tmp/tmp.vM73XtS5pe/flake-nixConfig.conf:/home/runner/.config/nix/nix.conf:
    _system: aarch64-linux
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Cachix: installing
  /usr/bin/bash -c nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
Cachix: checking version
  /home/runner/.nix-profile/bin/cachix --version
  /home/runner/.nix-profile/bin/cachix: 1: Syntax error: ")" unexpected
  Error: Action failed with error: Error: The process '/home/runner/.nix-profile/bin/cachix' failed with exit code 2

**Comment by domenkozar** [comment]
Can you give more details, does it happen all the time?

**Comment by 573** [comment]
Not an issue just a bit subtle, it disappears when I run `nixbuild/nix-quick-install-action@v25` AFTER any step that does:

```
sudo apt-get update
sudo apt-get install -y qemu-user-static
```

Seems to be more like a Q&A entry.

**Comment by SomeoneSerge** [comment]
Observing the same error, seemingly in the same setting:

1. The failing job: https://github.com/SomeoneSerge/llama.cpp/actions/runs/7371178604/job/20058298426
2. The job that had succeeded earlier: https://github.com/SomeoneSerge/llama.cpp/actions/runs/7367025606/job/20049815302. The difference between the jobs is that I've removed `apt ... install qemu-user-static` in the one that fails

The only thing I see in the logs (and that's not a very informative error message) is:

```
  /home/runner/.nix-profile/bin/cachix --version
  /home/runner/.nix-profile/bin/cachix: 1: Syntax error: "(" unexpected
  Error: Action failed with error: Error: The process '/home/runner/.nix-profile/bin/cachix' failed with exit code 2
```

**Comment by SomeoneSerge** [comment]
The reason seems to be that I've set `system = aarch64-linux` (isntead of `extra-paltforms = aarch64-linux`) in the `nix.conf`, so the cachix action has set up the aarch64 cachix (thanks to @philiptaron for navigating with this)

Maybe we could have the cachix action determine the host system manually (maybe based on `uname`) and import nixpkgs with the correct platform manually? Or plain error out if it sees a divergence
