### ISSUE TITLE
action hangs if signing key is wrong

### ISSUE THREAD

**Issue by chessai** [cachix/cachix-action#16]
i had my signing key set incorrectly (see my confusion in #15), and the cachix action succeeded on everything, until it was time to push to cachix. it was going for about 10 minutes, i went to lunch and came back, and it was still going. i think this should error instead.

**Comment by domenkozar** [comment]
That's because signing key won't be present on PRs. But I agree this should be handled in a better day.

**Comment by chessai** [comment]
What do you mean by "won't be present on PRs"? I thought that adding the signing key would be available for the initial PR. am i mistaken?

**Comment by domenkozar** [comment]
It's present on builds where the committer has write access. So if somebody makes a PR without write access, those builds won't be synced to cachix, but they will still substitute and build.

**Comment by domenkozar** [comment]
@chessai just to clarify, was it hanging in `cachix push` stage or in `nix-build`?

**Comment by chessai** [comment]
@domenkozar cachix push

**Comment by domenkozar** [comment]
That's surprising - could you share a link to that action log?

**Comment by chessai** [comment]
sure.

Note that the operation was cancelled after 1.5 hours of hanging and printing nothing:

```
Run cachix/cachix-action@v2
  with:
    name: layer-3-cachix
    signingKey: ***
  env:
    PATH: /usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/runner/.nix-profile/bin
    NIX_PATH: /nix/var/nix/profiles/per-user/runner/channels
Installing Cachix
  nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/ab5863afada3c1b50fc43bf774b75ea71b287cde
  unpacking 'https://github.com/NixOS/nixpkgs/tarball/ab5863afada3c1b50fc43bf774b75ea71b287cde'...
  installing 'cachix-0.3.4'
  these paths will be fetched (28.35 MiB download, 127.45 MiB unpacked):
 ...
 copying paths...omitted for brevity
 ...
  building '/nix/store/9f5wh188m9ddsnn64mfkpwsdjvvflahv-user-environment.drv'...
  created 22 symlinks in user environment
Cachix: using layer-3-cachix
  cachix use layer-3-cachix
  Configured https://layer-3-cachix.cachix.org binary cache in /home/runner/.config/nix/nix.conf
Invoking nix-build
  nix-build default.nix
Cachix: pushing to layer-3-cachix
  cachix push layer-3-cachix
  ##[error]The operation was canceled.
```

**Comment by domenkozar** [comment]
I wasn't able to reproduce this, with the wrong key I get:


```"{\"error\":\"Signature verification failed. The signing key you're using doesn't match any of the public keys for binary cache cachix. Fingerprint: 1;/nix/store/an98s6751qmwp25jzdzna5bsnz77cgrr-source;sha256:0fc5bgv9syfcblp23y05kkfnpgh3gssz6vn24frs8dzw39algk2z;45496;\"}"})```

Haven't seen such a report besides this, I'm going to close but feel free to reopen if you have some additional info!
