### ISSUE TITLE
When tokens get revoked the cachix-action hangs indefinitely

### ISSUE THREAD

**Issue by F-WRunTime** [cachix/cachix-action#164]
When running the cachix action and a token is revoked after a build the post hook hangs until it's killed by the runner or host. 

Expected result is builds are successfully pushed to the remote.

**Comment by sandydoo** [comment]
Do you have any logs to share? Of particular interest is whether it's taking a really long time because it's repeatedly retrying each failed push (a fix for which will be deployed soon), or it's an actual deadlock somewhere.

**Comment by domenkozar** [comment]
This should be fixed in Cachix 1.7, let us know if it happens again.
