### ISSUE TITLE
README: Talk about security issues

### ISSUE THREAD

**Issue by nomeata** [cachix/cachix-action#17]
Having set up cachix on travis before, I had to face the following questions:

 * Can someone who creates a PR (i.e. anyone) modify the build instructions to extract the private key to cachix?
 * Can someone who creates a PR (i.e. anyone) modify the build instructions to upload something to the cache that is _not_ actually the result of the derivation.
 * Can someone who can commit to `master` modify the build instructions to extract the private key to cachix?
 * Can someone who can commit to `master` modify the build instructions to upload something to the cache that is _not_ actually the result of the derivation.

Maybe the answers are obvious if you know GitHub Actions better than I do, but I would still appreciate a brief discussion of who I am trusting if I using this Github Action. Thanks!

**Comment by domenkozar** [comment]
From https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#using-encrypted-secrets-in-a-workflow:

> Anyone with write access to a repository can create, read, and use secrets.

Would it suffice adding that to the README, I think it answers all your questions, except the last one.

> Can someone who can commit to master modify the build instructions to upload something to the cache that is not actually the result of the derivation.

They can upload a nar+narinfo if they have access to signing key.

**Comment by nomeata** [comment]
> Would it suffice adding that to the README, I think it answers all your questions, except the last one.

I guess it would help. Or maybe a bold warning “Every developers who can push to a branch in your repository will be able to gainaccess to the signing key and can poison the cachix cache. Developers who work on forks and submit PRs cannot.”

**Comment by turboMaCk** [comment]
I also think it would be worth mentioning especially because cachix website states:

![image](https://user-images.githubusercontent.com/2130305/72364999-bcc3ec00-36f7-11ea-9322-e87839ef7be3.png)

So I think it might be easy to miss this aspect if one doesn't really pay attention and just follows both instructions blindly. I wouldn't call it a huge issue but certainly it would be better to have this clarified.

**Comment by domenkozar** [comment]
I agree. I will make cache creation more streamlined in a month or so.

**Comment by domenkozar** [comment]
See #17 and let me know if that needs further clarification.

**Comment by turboMaCk** [comment]
correct link: https://github.com/cachix/cachix-action/pull/42

Nice @domenkozar thanks! :clap:
