### ISSUE TITLE
Push to cachix in post run failed.

### ISSUE THREAD

**Issue by Ninlives** [cachix/cachix-action#173]
Recently I found my github action failed to push to cachix in the post run:
```
Post job cleanup.
Cachix: push
  /home/runner/.nix-profile/bin/cachix daemon stop --socket /home/runner/work/_temp/cachix-daemon-3xeRt1/daemon.sock
  [2024-02-21 06:06:20][Info] Starting Cachix Daemon
  [2024-02-21 06:06:20][Info] Configuration:
  PID: 100206
  Socket: /home/runner/work/_temp/cachix-daemon-3xeRt1/daemon.sock
  Workers: 8
  Cache name: emerge
  Cache URI: https://emerge.cachix.org/
  Cache public keys: ["emerge.cachix.org-1:Zvw8m0TXudK0MtylBFvUZCUEHlOfTgfvE2bbIexGhVw="]
  Cache is public: True
  Compression: ZSTD
  [2024-02-21 06:07:10][Info] Pushing /nix/store/nasnw9nvaapqnz0b0b3van7vnp4jdrhw-content.json
  [2024-02-21 06:07:10][Info] Pushing /nix/store/nyp298g5n1fml1hf68776x0fpzzazz8h-content.json
  [2024-02-21 06:07:10][Info] Failed /nix/store/nasnw9nvaapqnz0b0b3van7vnp4jdrhw-content.json
  [2024-02-21 06:07:10][Info] Failed /nix/store/nyp298g5n1fml1hf68776x0fpzzazz8h-content.json
  ......
```
I cannot find any error messages in the log. Could someone point the error in my configuration? The workflow file: https://github.com/Ninlives/emerge/blob/master/.github/workflows/ci.yml#L27

**Comment by sandydoo** [comment]
@Ninlives, the quick answer is that you should [create an `authToken`](https://app.cachix.org/cache/emerge/settings/authtokens) and replace the `signingKey` with it.

```yaml
- uses: cachix/cachix-action@v14
  with:
    name: emerge
    authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
```

The long story is that we're upgrading our auth system to eventually require auth tokens for all API access. From a security standpoint, we'd like to maintain separation between the auth and signing keys, and entirely avoid transmitting the signing key over the network. 
Self-signed caches are currently exempt and can continue being pushed to with just the signing key.

What appears to have happened is that the `emerge` cache was at some point converted to a managed cache, i.e. the signing key was given to Cachix to sign store paths on your behalf. Once converted, our backend used to allow you to continue using the signing key for authentication. We recently removed this edge-case. 

We'll update our docs and UI to reflect these changes. The intended way to transition in the future will be to first create new auth tokens; add them in addition to the signing key and verify that you can still push; then convert the cache and lastry remove the signing key.

We'll also update the action to display the error like it used to.

**Comment by Ninlives** [comment]
@sandydoo It works, thanks!
