### ISSUE TITLE
When running on self-hosted runner, tripped and started uploading absolutely everything

### ISSUE THREAD

**Issue by dpc** [cachix/cachix-action#179]
I'm playing with moving our CI to a self-hosted Github Runner, and I've noticed that post-action step failed with:

```
  /run/github-runner/runner-01-ff/_actions/cachix/cachix-action/v14/dist/main/push-paths.sh /nix/store/27hmcrn18aqa7fv35349ar3zhxkjca38-cachix-1.7-bin/bin/cachix  fedimint  
  sort: cannot read: /tmp/store-path-pre-build: No such file or directory
  Warning: /nix/store/invn3sjl8rx6fbmslx3f322vsxnjciwz-client-pkgs is not valid, skipping
  Warning: /nix/store/mwmplficrhc0wa06ixnv2wcz3y58xnj1-client-pkgs-group-aarch64-linux-android-ci-0.4.0-alpha is not valid, skipping
  Pushing 436 paths (7972 are already present) using zstd to cache fedimint ⏳
```

and started upload absolutely everything, including system paths to cachix. Not sure why `/tmp/store-path-pre-build` wasn't there (private tmp might have gotten created), but probably not a great failure mode one way or another.

**Comment by sandydoo** [comment]
Ah, process substitution footgun. We should at least add a check for that file. And maybe use `$TMP`/`$TMPDIR` for it.
