### ISSUE TITLE
cachix: CppStdException "Exception: path '/nix/store/... ' is not valid; type: nix::InvalidPath"

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix-action#3]
Example: https://github.com/tilpner/nur-packages/commit/a68e4bfaf5926f11694b40011cda2b2638e1af1a/checks?check_suite_id=249766848

**Comment by NorfairKing** [comment]
Another example here: https://github.com/NorfairKing/validity/commit/cb8ac139306a0745ca277f339e43d25b8c62e8af/checks?check_suite_id=249827005

**Comment by domenkozar** [comment]
This is fixed in master, will release v2 very shortly.

**Comment by NorfairKing** [comment]
Beautiful :heart:
