### ISSUE TITLE
v4 can not run nix-build on PR.

### ISSUE THREAD

**Issue by junjihashimoto** [cachix/cachix-action#30]
When we use pr, signingKey is empty.
So nix-build is not called.
https://github.com/cachix/cachix-action/blob/v4/src/main.ts#L32-L36

**Comment by domenkozar** [comment]
Can you try:

```
- uses: cachix/cachix-action@releases/v5
``

**Comment by junjihashimoto** [comment]
Thx! I will try it soon.

**Comment by junjihashimoto** [comment]
@domenkozar v5 works with pr.
Thank you very much.
