### ISSUE TITLE
Does nixBuildArgs support -E ?

### ISSUE THREAD

**Issue by 573** [cachix/cachix-action#32]
[x-ref](https://github.com/573/evcxr/runs/482070305)   

Using the newly introduced `nixBuildArgs: -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'` parameter cachix constructs `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}' default.nix` instead of expected `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'`.

Is there a way (i. e. setting `file` parameter) apart from rewriting my nix expression to overcome this situation ?

**Comment by domenkozar** [comment]
It needs to load expression from a file, is there any reason you can't do that?

**Comment by 573** [comment]
@domenkozar it's just my default.nix is 
```
{ callPackage, fetchFromGitHub, pkgconfig, buildRustCrateHelpers, defaultCrateOverrides, zeromq }:
with buildRustCrateHelpers;
let
  evcxr-src = fetchFromGitHub {
    owner = "google";
    repo = "evcxr";
    rev = "f375d872bb8560117780e7b9b83e9692e2cebb0e";
    sha256 = "19yaamv10dzgknjpwsilxd0s2hq60qxgjlcwsvvz63cxr6q3mjbh";
  };

  cratesIO = callPackage ./crates-io.nix {};

  _crates = callPackage ./Cargo.nix { inherit cratesIO; };

  evcxr_jupyter = (_crates.evcxr_jupyter {}).override {
    crateOverrides = defaultCrateOverrides // {
      evcxr = attrs: { src = evcxr-src; };
      evcxr_jupyter = attrs: { src = evcxr-src; };
      zmq-sys = attrs: { buildInputs = [ zeromq pkgconfig ]; };
    };
  };
in
  evcxr_jupyter
```
thus AFAIK have to use `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'`.

Can I rewrite the expression to simplify the nix-build call a bit ?

**Comment by domenkozar** [comment]
I would suggest moving your default.nix into pkg.nix and creating default.nix with `with import <nixpkgs> {}; callPackage ./pkg.nix {}`

**Comment by 573** [comment]
@domenkozar This works.
