### ISSUE TITLE
Push even if the build fails

### ISSUE THREAD

**Issue by rtimush** [cachix/cachix-action#33]
Until v4 the paths were pushed in parallel with the build, so the cache was populated even if the build would at the end fail. It seems that the current version updates the cache only if the build succeeds. This can be quite inconvenient for long builds. 
What do you think about running the `Cachix: Pushing paths` group even if `Invoking nix-build` failed?

**Comment by domenkozar** [comment]
Agreed, now that 0.3.7 is out I'll bring that back in.

**Comment by nomeata** [comment]
I just came around to report this. Especially in an early phase of a repository with dependencies that builds for an hour or more (think ghcjs) this would be very useful!

**Comment by domenkozar** [comment]
Planning to do this one in a couple of days.

**Comment by nomeata** [comment]
Thanks :)

**Comment by Mic92** [comment]
So does this still work in cachix-action-v4 or do I have to use cachix-action-v3?

**Comment by domenkozar** [comment]
This is fixed on master, I'm testing if it also works when the build timeouts.

**Comment by domenkozar** [comment]
Fixed via https://github.com/cachix/cachix-action/releases/tag/v6

WARNING: it's a breaking release, make sure to read changelog
