### ISSUE TITLE
Reproducibility broken by store-path-pre-build

### ISSUE THREAD

**Issue by ryantm** [cachix/cachix-action#36]
When the cachix-action does

`sh -c nix path-info --all | grep -v '.drv$' > store-path-pre-build`

It adds the file `store-path-pre-build` to the build directory, which affects reproducibility if the file isn't ignored.

Workaround for now: Add `store-path-pre-build` to filter sources or .gitignore if you are using [gitignore.nix](https://github.com/hercules-ci/gitignore.nix).

cc @domenkozar

**Comment by domenkozar** [comment]
Ouch :)

**Comment by domenkozar** [comment]
Fixed via https://github.com/cachix/cachix-action/releases/tag/v6 

WARNING: it's a breaking release, make sure to read changelog
