### ISSUE TITLE
System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix-action#43]
Currently linux worker doesn't have much free disk space on root, so it quickly runs out of disk space.

To mitigate running:

```
- run: sudo rm -rf /opt || true
```

helps, but also takes 13s. There's probably a faster way and I'm not sure we should include that in the action.

**Comment by Mic92** [comment]
Make it asynchronous maybe?

- run: sudo rm -rf /opt || true &

**Comment by domenkozar** [comment]
I'm afraid that someone might find /opt/ useful :/ I hope upstream fixed this.

**Comment by domenkozar** [comment]
According to https://github.com/actions/virtual-environments/issues/709#issuecomment-627265622 there should be 14GB of space now, which I think is sufficient for most builds.
