### ISSUE TITLE
cachix: CppStdException "Exception: path '/nix/store/xxxx-install' is not valid

### ISSUE THREAD

**Issue by pbogdan** [cachix/cachix-action#44]
Hi!

I'm trying to migrate to cachix v6 and am running into the following error:

```
/bin/sh -c nix path-info --all | grep -v '.drv$' | cat - /tmp/store-path-pre-build | sort | uniq -u  | /nix/var/nix/profiles/per-user/runner/profile/bin/cachix push nix-hie
  cachix: CppStdException "Exception: path '/nix/store/437pzy3m93xdnwknmw89wvhmc9w0vx2h-install' is not valid; type: nix::InvalidPath"
  ##[error]Action failed with error: Error: The process '/bin/sh' failed with exit code 1
  (node:4305) UnhandledPromiseRejectionWarning: Error: The process '/bin/sh' failed with exit code 1
      at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:907:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:890:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:790:27)
      at ChildProcess.emit (events.js:210:5)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  (node:4305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:4305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The full logs / set up of the repo are at https://github.com/pbogdan/nix-hie/pull/30

I'm not really sure if it's a user error but as I'm not really familiar with GitHub actions I don't know how to debug this further and / or correctly configure the action on my repo. I would really appreciate any help / pointers on how to fix this. Let me know if I can provide any other info.

**Comment by domenkozar** [comment]
Ah that's probably because you're doing GC. Do you really need to do that?

**Comment by pbogdan** [comment]
I was running out of disk space when building everything at once so I switched to an individual step per attribute with GC in between to conserve the disk space.

I think I will just switch to a separate job for each one instead - won't need GC or anything and should allow the builds to run in parallel too which is nice. I believe the issue I reported here shouldn't also be a problem anymore for me then.

**Comment by domenkozar** [comment]
I'd recommend `- run: sudo rm -rf /opt&` instead as it's faster.

**Comment by domenkozar** [comment]
Note that according to https://github.com/actions/virtual-environments/issues/709#issuecomment-627265622 there should be 14GB of free space so that should be sufficient now.

**Comment by pbogdan** [comment]
Thank you!
