### ISSUE TITLE
emacs built by home-manager not pushed to cachix

### ISSUE THREAD

**Issue by codygman** [cachix/cachix-action#50]
You can see in [this build](https://github.com/codygman/hci/runs/816607009?check_suite_focus=true) that emacs is compiled, so in [this build](https://github.com/codygman/hci/runs/816623803?check_suite_focus=true) I'd expect it to download from cache.

That doesn't seem to be the case though. Maybe the cachix action doesn't support things built by home-manager? My understanding was it went to look for different things in `/nix/store`.

**Comment by domenkozar** [comment]
@codygman looking at github actions log it doesn't seem it's using cachix-action?

**Comment by codygman** [comment]
[All is well now](https://github.com/codygman/hci/runs/821020748?check_suite_focus=true). Indeed, I just didn't add cachix to my github workflow file :sweat_smile:
