### ISSUE TITLE
nix-shell with fetchTarball not caching

### ISSUE THREAD

**Issue by silviogutierrez** [cachix/cachix-action#61]
First off: thanks for an amazing set of tools for GitHub actions. I'm slowly moving all my builds to just use nix in GitHub in addition to locally.

I've been using the install-nix-action without issue for a while. I'm trying to add caching to my open source project but can't seem to make it work. It's setup correctly, I believe. But the cache isn't picked up.

I imagine it's related to my esoteric, but warranted, use of `fetchTarball` to pin channels down to the commit.

You can see the PR here: https://github.com/silviogutierrez/reactivated/pull/54

And a successful run here: https://github.com/silviogutierrez/reactivated/pull/54/checks?check_run_id=1171142221

As well as the nix files in question here: https://github.com/silviogutierrez/reactivated/blob/8abffa2d5a080358dceb6083fe106ed7ad5fc814/shell.nix

Note: currently unstable and stable are the same commit, but this isn't always the case. They diverge often. So I can't just use `nix_path` in the action options. I need `fetchTarball` specifically.

And finally the GitHub actions conf here (Infrastructure job):

https://github.com/silviogutierrez/reactivated/blob/046be3b12ab9910eea42acc7c4f603402f2bade3/.github/workflows/ci.yaml

Any ideas how to get this to work? I'm using the built in action, so I don't think I need to follow this step: https://docs.cachix.org/faq.html#is-there-a-way-to-cache-nix-shell

Thanks for any help. And again, for the libraries and contributions.

**Comment by silviogutierrez** [comment]
To add a bit more info:

If I look at the action log, I do see it hitting cachix for say yarn (since that's overridden and "built" therefore not in the upstream cache).

But I guess I expected to skip that entire thing and this action to get the derivation hash of shell.nix, and go get the whole thing from cachix skipping the individual dependencies and just load the entire derivation that shell.nix produces.

Maybe this understanding is wrong!

**Comment by domenkozar** [comment]
Thanks!

You still need to download the full closure of all dependencies that you shell.nix uses.

In your particular case cachix isn't really that helpful, as all time consuming builds are from the upstream cache.

In case you would override something, then that will be uploaded to cachix for future builds.

I hope that clears it up :)

**Comment by silviogutierrez** [comment]
Thanks for the info. I realize that's now out of scope for cachix, but is there a specific reason it can't be added?

Even if it's a manual step and not seamless, it'd be pretty cool to do:

`cat shell.nix | cachix reactivated shell` or something and skip the whole process of getting the dependencies. Essentially, a "remote" friendly version of all these options: https://github.com/xzfc/cached-nix-shell#related

Just something to consider. I'm happy to sponsor this feature somehow.

Either way, thanks again.

**Comment by domenkozar** [comment]
@silviogutierrez I'm not sure I understand how that would work.

nix-shell builds/downloads all derivations that depend on the shell you're activating.

cached-nix-shell speeds up the process of evaluation by caching previous invocations (something that flakes can do too).

The part of having all dependencies available is easy to do locally since it's all there, on GitHub hosted runner nix store always starts empty.

I'm open to improvement though :)

**Comment by silviogutierrez** [comment]
@domenkozar : that's what I'm hoping to do. Basically, warm "/nix/store" on GitHub runners. It may be as simple as just using the built-in GitHub Cache action. That's too blunt in general, but maybe it works.

I'm not sure what edge cases copying an existing /nix/store directly can cause. I feel like there must be a reason direct copying of files is not mentioned in the nix remote copying section. They all entail ssh, binding to a server, etc.

Going to close this now. Thanks for all your nix work.

**Comment by domenkozar** [comment]
That's correct, nix-shell will be warmed up as well!
