### ISSUE TITLE
Update the @actions/core package to v1.2.6 or greater

### ISSUE THREAD

**Issue by lorenzleutgeb** [cachix/cachix-action#63]
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by zimbatm** [comment]
GitHub will deprecate the old method "soon" and this would break the action.
![image](https://user-images.githubusercontent.com/3248/97912031-81f57800-1d4c-11eb-9ff2-e2a2d858972d.png)

Dependabot has submitted a PR but it doesn't pass the CI: https://github.com/cachix/cachix-action/pull/62

**Comment by flokli** [comment]
@zimbatm see https://github.com/cachix/cachix-action/pull/62#issuecomment-721624309

**Comment by domenkozar** [comment]
I've released install-action-v12, but I don't think cachix-action uses these commands at all?

**Comment by domenkozar** [comment]
Ah, it does issue once. I'll prepare the release.

**Comment by domenkozar** [comment]
Released v7!
