### ISSUE TITLE
Specify an "output" to push to cachix

### ISSUE THREAD

**Issue by NobbZ** [cachix/cachix-action#74]
Currently the action pushes everything to cachix that hasn't been in the store after cachix itself has been loaded.

This causes "sources" beeing pushed to cachix, which will never be downloaded and GC'd on the next occasion.

Allowing to specify a path in the filesystem, eg. to a `result` symlink which will then be pushed including its references would cause a decrease in bandwith usage for both sides, CI time and storage cost on cachix as it would probably decrease time necessary to calculate GC'able items.

**Comment by domenkozar** [comment]
See #75 that was implement (and will be released today) to filter out some stuff. 

This is a whitelisting approach that I'd like to support as well.
