### ISSUE TITLE
Should not run `nix-build` unconditionally

### ISSUE THREAD

**Issue by purcell** [cachix/cachix-action#8]
I'd like to be able to use `cachix-action` when testing a non-Nix project, but it appears to run `nix-build` unconditionally. Ideally, IMO, the action should install `cachix` and enable the named cache, but should not assume that the current project is to be built.

https://github.com/purcell/package-lint/blob/nix-actions/.github/workflows/test.yml

**Comment by purcell** [comment]
Also, these actions are great, thanks - I was just yesterday looking at writing an action that performed the nix setup and cachix enable steps as part of its setup work, and reusing your actions seems highly preferable.

**Comment by purcell** [comment]
I suspect a sane approach might be to only run `nix-build` if the signing key attribute is set, or if an attribute or file is specified.

**Comment by domenkozar** [comment]
What if we add `run: command` parameter that defaults to `nix-build ...`? That way you could just do `run: cat myfilewithstorepaths.txt`

**Comment by domenkozar** [comment]
@purcell do you wish to only use the caches and also avoid pusing?

**Comment by domenkozar** [comment]
Given those requirements, the api could look like this:

```yaml
- uses: cachix/cachix-action@v3
      with:
        mode: configure
        use: mycache mycache2
- ...
- uses: cachix/cachix-action@v3
      with:
        name: mycache
        sourceCommand: nix-build ci.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
```

**Comment by purcell** [comment]
> do you wish to only use the caches and also avoid pushing?

Yes, exactly: I'm using `cachix` purely as a binary cache in order to obtain upstream artifacts that are then used to test the code in the current project.

> Given those requirements, the api could look like this:

The `mode` option feels unnecessary IMO. When the signing key is unset, nothing can be pushed, so I feel that no command should (can!) be run in that case. And when `signingKey` is provided, the default (or overridden) command would be run - I like the idea of `sourceCommand` or `run` for this.

**Comment by domenkozar** [comment]
> When the signing key is unset, nothing can be pushed, so I feel that no command should (can!) be run in that case. 

That's not desired when using nix-build and in pull request mode - when signing key is not present since the author doesn't have write access.

**Comment by purcell** [comment]
Ah, yes, I see. Well, perhaps just a separate "use cachix" action for cachix "clients".

**Comment by domenkozar** [comment]
I was thinking to split it up, but then the maintenance cost is way too high. There's also a penalty fetching actions at each build, so having `mode` seems like a good compromise. I'm not too happy about `configure` value, but can't think of anything better.

**Comment by purcell** [comment]
> I was thinking to split it up, but then the maintenance cost is way too high. There's also a penalty fetching actions at each build, so having `mode` seems like a good compromise. I'm not too happy about `configure` value, but can't think of anything better.

Understood. I don't think there'd be more than two modes, so why not just have `build: false`, to override the default of `true`? In the meantime, for my use case in an action I wrote, I've inlined the cachix installation and `cachix use` invocation.

**Comment by chshersh** [comment]
I would love to see a command like `run` as well. IIUC, this action only does `nix-build` at the moment. But I would love to run tests on CI as well. For example, on Travis CI I run tests with the following command:

* https://github.com/chshersh/type-errors-pretty/blob/93f7f90c6b956bd5ab59645746c4a78e3f8d1676/.travis.yml#L27

**Comment by codygman** [comment]
I also have a use for this if I understand correctly. I nix-install a few things and then run [some tests in a shell script](https://github.com/codygman/my-emacs-everywhere/blob/master/test.sh) with emacs my small (for now) repo.

Since nix-build is called I get an error, but I'm imagining there's a way to just call my shell script in a nix expression that would make this work okay.

**Comment by domenkozar** [comment]
Best way to avoid this mess is to use nix build hook. Going to implement this soon.

**Comment by domenkozar** [comment]
Could you try with:

```yaml
- uses: cachix/cachix-action@releases/v3
      with:
        name: mycache
        skipNixBuild: true
```

**Comment by domenkozar** [comment]
I've just released `cachix/cachix-action@v3` that fixes this.
