### ISSUE TITLE
Cachix unable to write to the nix store

### ISSUE THREAD

**Issue by notquiteamonad** [cachix/cachix-action#82]
The following error is produced:

```plaintext
Run cachix/cachix-action@v10
  with:
    name: cachix-action
  env:
    NIX_PATH: nixpkgs=channel:nixos-unstable
Cachix: installing
  /usr/bin/bash -c nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
  error: path '/nix/store/q0lqpbbxcn2y4f23nhms7ncj7gvwbid1-cachix-0.6.0' does not exist and cannot be created
  Error: Action failed with error: Error: The process '/usr/bin/bash' failed with exit code 1
```

I've created a [minimal reproducible example repo](https://github.com/notquiteamonad/cachix82) which [fails when it uses the cachix action](https://github.com/notquiteamonad/cachix82/runs/2388744129?check_suite_focus=true)

**Comment by domenkozar** [comment]
That's because you have disabled https://cache.nixos.org :) That's one of the reasons why Cachix exists to avoid such errors.

See https://github.com/cachix/install-nix-action#how-do-i-add-a-binary-cache

**Comment by notquiteamonad** [comment]
Ah, thanks. I hadn't understood that the two were mutually exclusive. I've updated my example repo to use the correct caches for the benefit of anyone else finding this ticket. Cheers!
